# default config
baseurl = "https://rarebooksinstem.com"
languageCode = "en-us"
title = "Rare Books in STEM"
theme = "parsa-hugo"
summaryLength = "10"
pagination.pagerSize = 6
# google analytics
googleAnalytics = "" # example : UA-123-45
