# ----------------------------------------------------------------
# English language
# ----------------------------------------------------------------
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

# banner
[en.params.banner]
enable = true
heading = "Welcome to <br> Rare Books in STEM!"

[en.params.about_me]
# About widget
#title = "Welcome to Rare Books in STEM!"
image = "images/aerial-steam-carriage.jpg"
bio = "Collector of unique and interesting material in science, technology, engineering, and mathematics."
