# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "FAQ"
url = "faq/"
weight = 2

[[main]]
name = "About"
url = "about/"
weight = 3

# footer menu
[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "About"
url = "about/"
weight = 2
