#################### default parameters ############################
#logo = "logos/newlogo.png"
logo_width = "150px"
favicon = "icons/favicon-32x32.png"
# Meta data
# description = "This is meta description"
author = "Rare Books in STEM"
og_image = "/images/placeholder.jpg"
# copyright
theme_copyright = true
copyright = "Copyright 2025 Rare Books in STEM"
# custom script on header
custom_script= ""
# search
search = true
# widget
# widgets = ["about", "categories", "recommended"]
widgets = ["about"]
# main sections
mainSections = ["post"]

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"