# default config
baseurl = "https://rarebooksinstem.com"
languageCode = "en-us"
title = "Rare Books in STEM"
theme = "parsa-hugo"
summaryLength = "10"
pagination.pagerSize = 6
# google analytics
googleAnalytics = "" # example : UA-123-45

# output
[outputs]
home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe = true

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"


# deult parameter
[params]
logo = "images/newlogo.png"
home = "Home"
# theme layout ( two layout is available, "1" and "2" )
layout = "2"
# Meta data
description = "This is meta description"
# Preloader
preloader = true
# search
search = true
# about author
author = "Rare Books in STEM"
author_image = "images/aerial-steam-carriage.jpg"
bio = "This site is dedicated to rare books in science, technology, engineering, and mathematics."
# Contact info
# mobile = "+90 000 333 22"
email = "rarebooksinstem@gmail.com"
# address = "6 rip carl Avenue CA 90733"
# Contact Form Action
contact_form_action = "#"
# copyright
copyright = "Copyright &copy; 2025 Rare Books in STEM"

# cookies
[params.cookies]
enable = true
expire_days = 2

# social site
#[[params.social]]
#icon = "ti-facebook"
#link = "https://facebook.com/themefisher"
