#################### default parameters ############################
logo = "images/logo.png"
logo_width = "150px"
favicon = "images/favicon.png"
# Meta data
description = "This is meta description"
author = "Themefisher"
og_image = "/images/placeholder.jpg"
# copyright
theme_copyright = true
copyright = "Copyright by your company"
# custom script on header
custom_script= ""
# search
search = true
# widget
widgets = ["about", "categories", "recommended"]
# main sections
mainSections = ["posts"]

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"